/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { Html, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    monitor007_low_monitor_0: THREE.Mesh
    monitor001_low_monitor_0: THREE.Mesh
    monitor002_low_monitor_0: THREE.Mesh
    monitor003_low_monitor_0: THREE.Mesh
    monitor_low_monitor_0: THREE.Mesh
    monitor008_low_monitor_0: THREE.Mesh
  }
  materials: {
    monitor: THREE.MeshStandardMaterial
  }
}

export function Monitor(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('models/car/RadioMonitor.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.026}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.monitor007_low_monitor_0.geometry}
            material={materials.monitor}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.monitor001_low_monitor_0.geometry}
            material={materials.monitor}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.monitor002_low_monitor_0.geometry}
            material={materials.monitor}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.monitor003_low_monitor_0.geometry}
            material={materials.monitor}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.monitor_low_monitor_0.geometry}
            material={materials.monitor}
            position={[0, 2.588, 7.366]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.monitor008_low_monitor_0.geometry}
            material={materials.monitor}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <Html className='w-[490px] h-[335px] bg-[#f0f0f0] rounded-[45px] overflow-y-auto p-0' rotation-x={1.25} position={[0, -4.33, 4.62]} transform occlude >
              <div className='p-10 w-[400px] h-[432px] scale-50 origin-top-left'>NIGGA</div>
            </Html>
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/car/RadioMonitor.glb')
